### ISSUE TITLE
Spring Rest Docs 적용하기

### ISSUE THREAD

**Issue by janeljs** [Sc0up/scoup-backend#155]
Spring Rest Docs를 학습한 뒤 적용한다. 
---
https://github.com/Sc0up/scoup-backend/discussions/131#discussioncomment-1357350

**Comment by janeljs** [comment]
### spring rest docs 설명
https://youtu.be/BFme2t9KSwA

**Comment by Dae-Hwa** [comment]
https://github.com/Sc0up/scoup-backend/discussions/131#discussioncomment-1357350

**Comment by Dae-Hwa** [comment]
path parameter 적용 하려면 `when.get(path)` 와 같이 호출해야함

https://github.com/spring-projects/spring-restdocs/blob/main/docs/src/test/java/com/example/restassured/PathParameters.java
