### ISSUE TITLE
그룹 수정(PUT /api/groups/{id}) API response

### ISSUE THREAD

**Issue by Dae-Hwa** [Sc0up/scoup-backend#195]
그룹 수정의 경우 204 No Content가 되야 할 것으로 보입니다.
POST가 아닌 PUT이기 때문에 테스트에서도 이미 id를 아는 상태이기 때문에 굳이 id 리턴을 할 필요 없어보입니다.

괜찮으면 해당 부분만 수정해서 pr 올려도 될까요?

**Comment by janeljs** [comment]
네 좋아요!☺

**Comment by min27604** [comment]
좋습니다!
