### ISSUE TITLE
[4-1-2] 일정상세 조회

### ISSUE THREAD

**Issue by Dae-Hwa** [Sc0up/scoup-backend#244]
### 인수 조건
SECTION|CONTENT
--|--
**Target**| group member
**Given**|  일정 ID로
**When**| 선택한 일정 정보를 조회하면
**Then**| 선택한 일정에 대한 정보가 전달된다.

**Comment by sanoeul** [comment]
오랜만에 놀러 왔는데 꾸준히 진행중 이시군요! 멋져요!👏
