### ISSUE TITLE
AcceptanceTestBase에 공통적인 ignoringFields 추가

### ISSUE THREAD

**Issue by Dae-Hwa** [Sc0up/scoup-backend#27]
User에 `BaseEntity` 적용 후 아래와 같은 코드를 작성하게 됐습니다.

![image](https://user-images.githubusercontent.com/24666330/128845589-2bea6c95-0ead-46c5-aed3-1bfca3ff2bdd.png)
https://github.com/Sc0up/scoup-backend/pull/26/commits/e65f524c1dd6ccf9a1003e9965f512f09d41d78d

공통적으로 사용될 것 같은데, `AcceptanceTestBase` 에 해당 필드들의 스트링 값을 static하게 저장해두는게 어떨까요?

**Comment by janeljs** [comment]
전 좋아요!😄 그런데 ignoring field에 id값도 포함되어야 할까요? 디비를 테스트 때마다 초기화한다면 id는 빼도 되지 않을까 해서요🤔

**Comment by min27604** [comment]
매번 넣어줘야하나 했는데 좋아요!

**Comment by janeljs** [comment]
> > 전 좋아요!😄 그런데 ignoring field에 id값도 포함되어야 할까요? 디비를 테스트 때마다 초기화한다면 id는 빼도 되지 않을까 해서요🤔
> 
> 그러면 auto increment 되는 시퀀스의 초기화도 같이 진행되야겠네요!
> 
> 저는 생성 후에 response로 해당 리소스가 어디있는지 찾을 수 있을 것이라 판단해서 id는 굳이 검증이 필요없다고 판단했습니다.
> 다른 테스트에서도 email이나 nickname으로 조회를 하게 될거라 생각해서 id는 크게 의미가 없다 생각했습니다.
> 
> 그럼에도 공통 설정이니 두 가지 배열을 모두 저장해두는 것도 좋은 선택일 것 같네요! 이건 어떠신가요?

@Dae-Hwa 안 그래도 auto increment가 적용되는 id값은 rollback되지 않는 부분 때문에 고민이 되었는데요. 
그럼에도 불구하고, email이나 nickname와 같이 unique한 필드가 없는 객체에 대한 테스트를 진행할 때, 나머지 필드가 다 똑같은 두 객체를 구분하여 테스트를 할 수 있으려면 id 검증 또한 필요하다고 생각했어요! 저는 두 가지 배열 다 저장하는 방법 좋은 것 같습니다🙂
