### ISSUE TITLE
DTO용 어노테이션 만들기

### ISSUE THREAD

**Issue by Dae-Hwa** [Sc0up/scoup-backend#4]
DTO에 사용되는 어노테이션을 정의한다.

**Comment by janeljs** [comment]
### 관련 논의
- [Allow usage of annotations as meta-annotations](https://github.com/projectlombok/lombok/issues/557)

**Comment by janeljs** [comment]
ResponseDTO와 requestDTO용으로 사용할 어노테이션을 정의하고 싶었으나 `@Getter`, `@Setter` 등의 롬복 어노테이션은 meta annotatino으로 사용하는 것이 불가능하다. 많은 사람들이 위의 이슈에서 이를 요구했지만 아직은 지원하지 않는 기능인듯하다.

**Comment by janeljs** [comment]
### 참고 자
- [Implementing a Custom Lombok Annotation](https://www.baeldung.com/lombok-custom-annotation)

**Comment by Dae-Hwa** [comment]
그럼 data나 vo 어노테이션 사용하고 문제 발생하면 해결하는 식으로 할까요?

**Comment by janeljs** [comment]
그게 좋을지 조금 번거럽도 저희가 custom annotation로 등록하려고 했던 어노테이션만 사용하는 것이 좋을지 고민되네요😅

**Comment by janeljs** [comment]
@min27604 새리 생각은 어떠세요?

**Comment by min27604** [comment]
프레디 말씀대로 문제 발생하면 해결하는 쪽으로 가는 건 어떨까요?

**Comment by janeljs** [comment]
좋아요! 그럼 일단 그렇게 진행해봐요!ㅎㅎ  이슈는 다시 필요할 때까지 닫아둘게요🙂
