### ISSUE TITLE
인수 테스트 패키징 관련

### ISSUE THREAD

**Issue by Dae-Hwa** [Sc0up/scoup-backend#43]
지금 저랑 제인은
controller 패키지 안에 인수 테스트를 작성했는데
이대로 가는거 괜찮을까요?
아니면 전체 단위를 통합하는 의미에서 한 단계 위에 작성하는게 좋을까요

예를 들어 `com.postsquad.scoup.web.user.UserAcceptanceTest` 와 같이요

**Comment by Dae-Hwa** [comment]
> 저는 사실 한 단계 위에 작성했었다가 프레디꺼 보고 controller 밑으로 이동해놓긴 했어요ㅋㅋ

새리도 똑같이 말씀하시던데 ㅠㅠ 그럼 위로 이동하는게 낫겠네요

**Comment by janeljs** [comment]
![image](https://user-images.githubusercontent.com/68000537/129206305-7fc8cf56-0ae1-48e2-8bef-1db2e9a8b71f.png)
그런데 지금 보낸 pr에는 이렇게 한 단계 위에 작성되어 있고, controller 패키지 아래로 수정한 건 아직 pr을 안 보냈는데 어디서 보신 건지 모르겠네요ㅎㅎ 넵! 그럼 다시 위로 이동해서 커밋할게요!

**Comment by Dae-Hwa** [comment]
> ![image](https://user-images.githubusercontent.com/68000537/129206305-7fc8cf56-0ae1-48e2-8bef-1db2e9a8b71f.png)
> 그런데 지금 보낸 pr에는 이렇게 한 단계 위에 작성되어 있고, controller 패키지 아래로 수정한 건 아직 pr을 안 보냈는데 어디서 보신 건지 모르겠네요ㅎㅎ 넵! 그럼 다시 위로 이동해서 커밋할게요!

방금 체크아웃해서 봤습니다 ㅋㅋㅋㅋ

**Comment by Dae-Hwa** [comment]
@min27604 이번 pr에서 새리도 위로 옮기셔도 무방할 것 같아요
